### ISSUE TITLE
DLL Hijacking vulnerability

### ISSUE THREAD

**Issue by ericlaw1979** [WPO-Foundation/win-shaper#1]
WinShaper elevates to admin. It suffers from a DLL hijacking bug (https://textslashplain.com/2015/12/18/dll-hijacking-just-wont-die/) whereby trojaned DLLs can be loaded into its elevated context.

`DLL Hijacked
C:\Users\elawrence\Downloads\old\winShaper.exe
is vulnerable to DLL Hijacking via
C:\Users\elawrence\Downloads\old\dwmapi.dll`

Maybe call [SetDefaultDLLDirectories](https://msdn.microsoft.com/en-us/library/windows/desktop/hh310515(v=vs.85).aspx) and or do any preloads needed? https://github.com/kichik/nsis/commit/e838208e4bc48306c2c65b1d6144de2509e8fd52

**Comment by pmeenan** [comment]
Thanks. Any chance you can re-test (the release was updated in-place)?  I just want to be sure that MFC isn't causing stuff to be loaded before I get a crack at setting the default directories.

**Comment by ericlaw1979** [comment]
I've confirmed the fix on Windows 10. Thanks for the fast turnaround!
