### ISSUE TITLE
Command Line Usage

### ISSUE THREAD

**Issue by marty90** [WPO-Foundation/win-shaper#12]
Hi!
Is it possible to use the tool from the command line?

**Comment by marty90** [comment]
If I run:
```
.\bin\shaper.exe install
```
I get:
`Failed to start the service`

I am using windows 10, Power Shell as Admininstrator

**Comment by marty90** [comment]
I managed to make it work, disabling driver signature!

**Comment by pmeenan** [comment]
Yep, sorry - I don't have an EV code signing cert for kernel drivers and the $$$ for it was too hard to justify for just this project ($300-$500 per year).

**Comment by marty90** [comment]
Thank you for developing the tool :)
It is just a bit cumbersome to disable driver signature :(
