### ISSUE TITLE
Compiling source code

### ISSUE THREAD

**Issue by PankajKaushik78** [WPO-Foundation/win-shaper#13]
Hey, I am trying to compile the source code to generate a new binary like the one present in `bin/shaper.exe`.
I am able to compile the [exe.cpp](https://github.com/WPO-Foundation/win-shaper/blob/master/exe/exe.cpp) and generate a new binary like this
`g++ exe.cpp -lShlwapi -o throttle.exe`
But when I try to run `throttle.exe install` I get the following error `Failed to start the service`

I have tried it on windows 8 and windows 10.
g++ version:  4.6.3 

Is this the correct way to compile the code and make CLI work? If not, can someone help out with steps to compile this code.

**Comment by pmeenan** [comment]
Have you tried visual studio community edition?  I've never tried compiling it with g++.

That said, installing the driver on a modern Windows machine requires either disabling secure boot or getting a kernel signing certificate and signing the binary.  Could you get it working with the pre-built binaries and just not with a self-built?  If so then it's likely the build environment.  If not then it is probably the driver signing.

**Comment by PankajKaushik78** [comment]
Yes, it is working with pre-built binaries. Looks like an issue with build environment. Will try out with visual studio community edition.

**Comment by PankajKaushik78** [comment]
@pmeenan I have tried to build it with visual studio community edition. It is showing `Failed to open the service control manager`. I have directly compiled the `exe.cpp` file via visual studio. Also, is it supposed to generate new `shaper32.sys` and `shaper64.sys` files along with it? Because it is not generating it right now.

I am new to this and I think i am missing some step here. Can you share the steps to compile the code. Would be helpful if we can document it :)

**Comment by pmeenan** [comment]
You don't compile individual code files, you open the .sln at the root of the project which has build targets for everything and do a build-all.

You likely need a Windows platform SDK and DDK as well if you don't have those installed.

And given the code was last touched several years ago, if you are using a newer visual studio, SDK and DDX, you may need to handle any changes that come as a result.

**Comment by PankajKaushik78** [comment]
@pmeenan I have tried to compile it with various Visual studio versions but i am not able to make it work. Currently, I am trying to run in on Visual Studio 17, and I am stuck on this error
`error LNK2001: unresolved external symbol __guard_eh_cont_table`

Complete output from the build is:
`1>------ Build started: Project: exe, Configuration: Debug x64 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
1>exe.vcxproj -> C:\Users\Himanshu\Desktop\win-shaper-master\x64\Debug\shaper.exe
1>exe.vcxproj -> C:\Users\Himanshu\Desktop\win-shaper-master\x64\Debug\shaper.pdb (Full PDB)
1>Done building project "exe.vcxproj".
2>------ Build started: Project: shaper, Configuration: Debug x64 ------
2>Building 'shaper' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
2>BufferOverflowFastFailK.lib(loadcfg.obj) : error LNK2001: unresolved external symbol __guard_eh_cont_table
2>BufferOverflowFastFailK.lib(loadcfg.obj) : error LNK2001: unresolved external symbol __guard_eh_cont_count
2>C:\Users\Himanshu\Desktop\win-shaper-master\x64\Debug\shaper64.sys : fatal error LNK1120: 2 unresolved externals
2>Done building project "shaper.vcxproj" -- FAILED.
3>------ Build started: Project: gui, Configuration: Debug x64 ------
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(400,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build.
3>gui.vcxproj -> C:\Users\Himanshu\Desktop\win-shaper-master\x64\Debug\winShaper.exe
3>gui.vcxproj -> C:\Users\Himanshu\Desktop\win-shaper-master\x64\Debug\winShaper.pdb (Partial PDB)
3>Done building project "gui.vcxproj".
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

What can be done here? 
It would be helpful if you can share the versions of VS, SDK and DDK that you have used to build the project

**Comment by pmeenan** [comment]
If Google search is correct, those sound like SDK mismatches. It's been 5 years since I've built the project, I have no idea what versions of the compiler, SDK and DDK were around then.

From the .sln, it looks like version 14 of the compiler (VS17) so you likely have the correct version of that, just the Windows SDK and DDK (probably an early Windows 10 SDK and DDK).

I don't think it matters, but I was also likely using the full commercial version of Visual Studio at the time.
