### ISSUE TITLE
Does winShaper make external network calls?

### ISSUE THREAD

**Issue by PankajKaushik78** [WPO-Foundation/win-shaper#14]
Hey, hybrid-analysis report indicates that winShaper makes external network calls. Is it true? If yes then, can you please share the module in source code where we are doing it and may be why we are doing it?

<img width="396" alt="image-20220406-151428" src="https://user-images.githubusercontent.com/22210915/162420615-944911d1-3850-4943-91e5-d9045e27ffb7.png">

More details of hybrid-analysis report can be found here https://www.hybrid-analysis.com/sample/cc3fc53b121ba84adb354a5474c6cce6a25e351fa18f022f81e24cb7ec969bff/5a00d4587ca3e13a260d44f3

**Comment by pmeenan** [comment]
Nope. Not sure how they run their analysis but that looks like a string that came from "network.pcap" which is a HEAD request for a Chrome update (none of which are part of winshaper).
