### ISSUE TITLE
Outbound throttle seems inaccurate

### ISSUE THREAD

**Issue by ericlaw1979** [WPO-Foundation/win-shaper#4]
E.g. setting to 1.5mbps/384kbps shows 1.24mbps down and 2.67mbps up on speedtest.net, setting to 780kbps/330kpbs shows 0.73 down and 2.75 up. Similar results on speakeasy.net/speedtest

WinShaper v1.0 (latest); Win10 x64 14986.1001

**Comment by pmeenan** [comment]
For my sanity, can you try uploading a large file somewhere (or copying across the network) and seeing what the actual transfer rate looks like?

**Comment by ericlaw1979** [comment]
Interesting; if I use Windows Explorer to copy across the network, the performance does not exceed the configured value (it's actually about 1/3 as fast, e.g. 111kbps for the 384kpbs setting). 

I need to find or build a website that calculates INPUT TYPE=FILE upload speed and see whether this is some sort of browser-specific thing.

**Comment by pmeenan** [comment]
Strangely, I can't reproduce it so I wonder if there is maybe some interaction going on with other bits of the net stack.

![image](https://cloud.githubusercontent.com/assets/444165/21362069/c6334f08-c6b4-11e6-81ce-72c54814aba7.png)

I generally disable Windows' QOS and other filter drivers on my main desktop.  I'll see if I can reproduce it in a VM.  You are running the bleeding-edge insiders build of 10, right?

I also tested with WinSCP to upload large files to a local server and it stabelized around 44KB/s which is about right though it took a while before congestion control came to it's senses.  There was a flood of data filling the queue until packet loss kicked in and the queue drained - repeat a few times and then it hit a happy equilibrium.

**Comment by ericlaw1979** [comment]
Interesting. I tried on another Win10 PC (also v14986, the latest) and got the same results. I notice now that both of the test sites I mentioned were based on Ookla technology. Both PCs are connected via wifi.

When I try on my Google desktop at work (Win10 v10586, wired LAN connection) the numbers returned by the test sites match expectations.

**Comment by pmeenan** [comment]
I'm heading out of town for a week so it'll be a while before I can try it out but I'll take a look as soon as I get back.  I'll try a mix of stable/insider and wifi/LAN to see if I can find a combination that reproduces it.  Current theory is that maybe the packet size information isn't returning correctly for outbound WiFi packets which would throw off the bandwidth throttling.

**Comment by pmeenan** [comment]
Just released [1.0.0.2](https://github.com/WPO-Foundation/win-shaper/releases/tag/winshaper_1.0.0.2) with the fix
