### ISSUE TITLE
Packet Loss edit control does not accept fractional percentages

### ISSUE THREAD

**Issue by wurdack** [WPO-Foundation/win-shaper#6]
The edit control for packet loss (IDC_PLR) is marked ES_NUMBER, which prevents you from typing a decimal percentage, despite the fact that SHAPER_PARAMS supports .01% granularity.

The net result (for me) is that the smallest packet loss I can get is 1%, which is enough to trigger crazy shenanigans in SMB that don't represent my test scenario very well.

**Comment by pmeenan** [comment]
Just released [1.0.0.2](https://github.com/WPO-Foundation/win-shaper/releases/tag/winshaper_1.0.0.2) with the fix

**Comment by wurdack** [comment]
Fabulous, thanks!
